[package]
name = "lowbench"
version = "0.1.2"
edition = "2024"

description = "A tiny benchmarking utility for Rust."
license = "MIT"
readme = "README.md"
repository = "https://github.com/vhhnrrrpby-beep/lowbench"

keywords = ["benchmark", "performance", "profiling"]
categories = ["development-tools::profiling"]

[dependencies]

[features]
default = ["std"]
std = []